// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: voice_shortcut.
// - Entity ID: 102019b2305f2377cab9d18c3b5fc7a12c7.
// - Entity Version: 102019b27a76a5f707fbe6865c0e6e7378a.
// - Task ID: 69417266b7d5b6b87ea7d926.
// - Task Root ID: 6931ddab540058f9d7a435e5.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for VoiceShortcutModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface VoiceShortcutModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  trigger_phrase: string;
  expansion_text: string;
  is_enabled: boolean;
}

/**
 * ORM class for VoiceShortcut entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class VoiceShortcutORM {
  private static instance: VoiceShortcutORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b2305f2377cab9d18c3b5fc7a12c7';
    this.entityName = 'voice_shortcut';
    this.entityVersion = '102019b27a76a5f707fbe6865c0e6e7378a';
    this.taskId = '69417266b7d5b6b87ea7d926';
    this.taskRootId = '6931ddab540058f9d7a435e5';
  }

  /**
   * Get singleton instance of VoiceShortcutORM
   */
  public static getInstance(): VoiceShortcutORM {
    if (!VoiceShortcutORM.instance) {
      VoiceShortcutORM.instance = new VoiceShortcutORM();
    }
    
    return VoiceShortcutORM.instance;
  }

  /**
   * Get all VoiceShortcut records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllVoiceShortcut(): Promise<VoiceShortcutModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new VoiceShortcut record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertVoiceShortcut(data: VoiceShortcutModel[]): Promise<VoiceShortcutModel[]> {
    const structured = data.map((item) => CreateData(VoiceShortcutModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all VoiceShortcut records
   */
  async purgeAllVoiceShortcut(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List VoiceShortcut records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listVoiceShortcut(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[VoiceShortcutModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get voice_shortcut by Id index
   * This function gets data by index.
   */
  async getVoiceShortcutById(
    id: string,
  ): Promise<VoiceShortcutModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voice_shortcut by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVoiceShortcutById(
    id: string,
    data: VoiceShortcutModel
  ): Promise<VoiceShortcutModel[]> {
    const index = createIndexId(
      id
    );

    const values = VoiceShortcutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voice_shortcut by Id index
   */
  async deleteVoiceShortcutById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get voice_shortcut by DataCreator index
   * This function gets data by index.
   */
  async getVoiceShortcutByDataCreator(
    data_creator: string,
  ): Promise<VoiceShortcutModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voice_shortcut by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVoiceShortcutByDataCreator(
    data_creator: string,
    data: VoiceShortcutModel
  ): Promise<VoiceShortcutModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = VoiceShortcutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voice_shortcut by DataCreator index
   */
  async deleteVoiceShortcutByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get voice_shortcut by DataUpdater index
   * This function gets data by index.
   */
  async getVoiceShortcutByDataUpdater(
    data_updater: string,
  ): Promise<VoiceShortcutModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voice_shortcut by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVoiceShortcutByDataUpdater(
    data_updater: string,
    data: VoiceShortcutModel
  ): Promise<VoiceShortcutModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = VoiceShortcutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voice_shortcut by DataUpdater index
   */
  async deleteVoiceShortcutByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get voice_shortcut by TriggerPhraseUserId index
   * This function gets data by index.
   */
  async getVoiceShortcutByTriggerPhraseUserId(
    trigger_phrase: string,
    user_id: string,
  ): Promise<VoiceShortcutModel[]> {
    const index = createIndexTriggerPhraseUserId(
      trigger_phrase,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voice_shortcut by TriggerPhraseUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVoiceShortcutByTriggerPhraseUserId(
    trigger_phrase: string,
    user_id: string,
    data: VoiceShortcutModel
  ): Promise<VoiceShortcutModel[]> {
    const index = createIndexTriggerPhraseUserId(
      trigger_phrase,
      user_id
    );

    const values = VoiceShortcutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voice_shortcut by TriggerPhraseUserId index
   */
  async deleteVoiceShortcutByTriggerPhraseUserId(
    trigger_phrase: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexTriggerPhraseUserId(
      trigger_phrase,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to VoiceShortcutModel data array
   */
  private resultToData(values: Data[]): VoiceShortcutModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return VoiceShortcutModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as VoiceShortcutModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized VoiceShortcutModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is VoiceShortcutModel => item !== null);
  }
}

/**
 * Convert VoiceShortcutModel data to Value array
 */
function VoiceShortcutModelToValues(data: VoiceShortcutModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'trigger_phrase', type: DataType.string, defaultValue: '' },
    { key: 'expansion_text', type: DataType.string, defaultValue: '' },
    { key: 'is_enabled', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof VoiceShortcutModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to VoiceShortcutModel data
 */
function VoiceShortcutModelFromValues(values: Value[]): VoiceShortcutModel {
  const data: Partial<VoiceShortcutModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'trigger_phrase':
        data.trigger_phrase = ParseValue(value, DataType.string) as string;
        break;
      case 'expansion_text':
        data.expansion_text = ParseValue(value, DataType.string) as string;
        break;
      case 'is_enabled':
        data.is_enabled = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as VoiceShortcutModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for TriggerPhraseUserId fields
 */
function createIndexTriggerPhraseUserId(
  trigger_phrase: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, trigger_phrase, 'trigger_phrase'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['trigger_phrase', 'user_id'],
    values
  };
}

export default VoiceShortcutORM;