// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: voice_training_sample.
// - Entity ID: 102019b2305f23776ba8079bb2160bd280a.
// - Entity Version: 102019b27a76a5f707fbe6865c0e6e7378a.
// - Task ID: 69417266b7d5b6b87ea7d926.
// - Task Root ID: 6931ddab540058f9d7a435e5.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for VoiceTrainingSampleModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface VoiceTrainingSampleModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  profile_id: string;
  audio_file_url: string;
  duration: number;
}

/**
 * ORM class for VoiceTrainingSample entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class VoiceTrainingSampleORM {
  private static instance: VoiceTrainingSampleORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b2305f23776ba8079bb2160bd280a';
    this.entityName = 'voice_training_sample';
    this.entityVersion = '102019b27a76a5f707fbe6865c0e6e7378a';
    this.taskId = '69417266b7d5b6b87ea7d926';
    this.taskRootId = '6931ddab540058f9d7a435e5';
  }

  /**
   * Get singleton instance of VoiceTrainingSampleORM
   */
  public static getInstance(): VoiceTrainingSampleORM {
    if (!VoiceTrainingSampleORM.instance) {
      VoiceTrainingSampleORM.instance = new VoiceTrainingSampleORM();
    }
    
    return VoiceTrainingSampleORM.instance;
  }

  /**
   * Get all VoiceTrainingSample records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllVoiceTrainingSample(): Promise<VoiceTrainingSampleModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new VoiceTrainingSample record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertVoiceTrainingSample(data: VoiceTrainingSampleModel[]): Promise<VoiceTrainingSampleModel[]> {
    const structured = data.map((item) => CreateData(VoiceTrainingSampleModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all VoiceTrainingSample records
   */
  async purgeAllVoiceTrainingSample(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List VoiceTrainingSample records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listVoiceTrainingSample(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[VoiceTrainingSampleModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get voice_training_sample by Id index
   * This function gets data by index.
   */
  async getVoiceTrainingSampleById(
    id: string,
  ): Promise<VoiceTrainingSampleModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voice_training_sample by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVoiceTrainingSampleById(
    id: string,
    data: VoiceTrainingSampleModel
  ): Promise<VoiceTrainingSampleModel[]> {
    const index = createIndexId(
      id
    );

    const values = VoiceTrainingSampleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voice_training_sample by Id index
   */
  async deleteVoiceTrainingSampleById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get voice_training_sample by DataCreator index
   * This function gets data by index.
   */
  async getVoiceTrainingSampleByDataCreator(
    data_creator: string,
  ): Promise<VoiceTrainingSampleModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voice_training_sample by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVoiceTrainingSampleByDataCreator(
    data_creator: string,
    data: VoiceTrainingSampleModel
  ): Promise<VoiceTrainingSampleModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = VoiceTrainingSampleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voice_training_sample by DataCreator index
   */
  async deleteVoiceTrainingSampleByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get voice_training_sample by DataUpdater index
   * This function gets data by index.
   */
  async getVoiceTrainingSampleByDataUpdater(
    data_updater: string,
  ): Promise<VoiceTrainingSampleModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voice_training_sample by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVoiceTrainingSampleByDataUpdater(
    data_updater: string,
    data: VoiceTrainingSampleModel
  ): Promise<VoiceTrainingSampleModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = VoiceTrainingSampleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voice_training_sample by DataUpdater index
   */
  async deleteVoiceTrainingSampleByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get voice_training_sample by ProfileId index
   * This function gets data by index.
   */
  async getVoiceTrainingSampleByProfileId(
    profile_id: string,
  ): Promise<VoiceTrainingSampleModel[]> {
    const index = createIndexProfileId(
      profile_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voice_training_sample by ProfileId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVoiceTrainingSampleByProfileId(
    profile_id: string,
    data: VoiceTrainingSampleModel
  ): Promise<VoiceTrainingSampleModel[]> {
    const index = createIndexProfileId(
      profile_id
    );

    const values = VoiceTrainingSampleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voice_training_sample by ProfileId index
   */
  async deleteVoiceTrainingSampleByProfileId(
    profile_id: string
  ): Promise<void> {
    const index = createIndexProfileId(
      profile_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to VoiceTrainingSampleModel data array
   */
  private resultToData(values: Data[]): VoiceTrainingSampleModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return VoiceTrainingSampleModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as VoiceTrainingSampleModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized VoiceTrainingSampleModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is VoiceTrainingSampleModel => item !== null);
  }
}

/**
 * Convert VoiceTrainingSampleModel data to Value array
 */
function VoiceTrainingSampleModelToValues(data: VoiceTrainingSampleModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'profile_id', type: DataType.string, defaultValue: '' },
    { key: 'audio_file_url', type: DataType.string, defaultValue: '' },
    { key: 'duration', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof VoiceTrainingSampleModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to VoiceTrainingSampleModel data
 */
function VoiceTrainingSampleModelFromValues(values: Value[]): VoiceTrainingSampleModel {
  const data: Partial<VoiceTrainingSampleModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'profile_id':
        data.profile_id = ParseValue(value, DataType.string) as string;
        break;
      case 'audio_file_url':
        data.audio_file_url = ParseValue(value, DataType.string) as string;
        break;
      case 'duration':
        data.duration = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as VoiceTrainingSampleModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for ProfileId fields
 */
function createIndexProfileId(
  profile_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, profile_id, 'profile_id'),
  ];

  return {
    fields: ['profile_id'],
    values
  };
}

export default VoiceTrainingSampleORM;