// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: dictation_correction.
// - Entity ID: 102019b22e952f17aa98cdf7b75e4a987d9.
// - Entity Version: 102019b27a76a5f707fbe6865c0e6e7378a.
// - Task ID: 69417266b7d5b6b87ea7d926.
// - Task Root ID: 6931ddab540058f9d7a435e5.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for DictationCorrectionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface DictationCorrectionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  profile_id: string;
  original_audio_url: string;
  spoken_text: string;
  corrected_text: string;
  audio_duration: number;
  is_applied: boolean;
}

/**
 * ORM class for DictationCorrection entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class DictationCorrectionORM {
  private static instance: DictationCorrectionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b22e952f17aa98cdf7b75e4a987d9';
    this.entityName = 'dictation_correction';
    this.entityVersion = '102019b27a76a5f707fbe6865c0e6e7378a';
    this.taskId = '69417266b7d5b6b87ea7d926';
    this.taskRootId = '6931ddab540058f9d7a435e5';
  }

  /**
   * Get singleton instance of DictationCorrectionORM
   */
  public static getInstance(): DictationCorrectionORM {
    if (!DictationCorrectionORM.instance) {
      DictationCorrectionORM.instance = new DictationCorrectionORM();
    }
    
    return DictationCorrectionORM.instance;
  }

  /**
   * Get all DictationCorrection records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllDictationCorrection(): Promise<DictationCorrectionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new DictationCorrection record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertDictationCorrection(data: DictationCorrectionModel[]): Promise<DictationCorrectionModel[]> {
    const structured = data.map((item) => CreateData(DictationCorrectionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all DictationCorrection records
   */
  async purgeAllDictationCorrection(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List DictationCorrection records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listDictationCorrection(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[DictationCorrectionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get dictation_correction by Id index
   * This function gets data by index.
   */
  async getDictationCorrectionById(
    id: string,
  ): Promise<DictationCorrectionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) dictation_correction by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDictationCorrectionById(
    id: string,
    data: DictationCorrectionModel
  ): Promise<DictationCorrectionModel[]> {
    const index = createIndexId(
      id
    );

    const values = DictationCorrectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete dictation_correction by Id index
   */
  async deleteDictationCorrectionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get dictation_correction by DataCreator index
   * This function gets data by index.
   */
  async getDictationCorrectionByDataCreator(
    data_creator: string,
  ): Promise<DictationCorrectionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) dictation_correction by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDictationCorrectionByDataCreator(
    data_creator: string,
    data: DictationCorrectionModel
  ): Promise<DictationCorrectionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = DictationCorrectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete dictation_correction by DataCreator index
   */
  async deleteDictationCorrectionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get dictation_correction by DataUpdater index
   * This function gets data by index.
   */
  async getDictationCorrectionByDataUpdater(
    data_updater: string,
  ): Promise<DictationCorrectionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) dictation_correction by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDictationCorrectionByDataUpdater(
    data_updater: string,
    data: DictationCorrectionModel
  ): Promise<DictationCorrectionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = DictationCorrectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete dictation_correction by DataUpdater index
   */
  async deleteDictationCorrectionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get dictation_correction by UserId index
   * This function gets data by index.
   */
  async getDictationCorrectionByUserId(
    user_id: string,
  ): Promise<DictationCorrectionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) dictation_correction by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDictationCorrectionByUserId(
    user_id: string,
    data: DictationCorrectionModel
  ): Promise<DictationCorrectionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = DictationCorrectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete dictation_correction by UserId index
   */
  async deleteDictationCorrectionByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get dictation_correction by ProfileId index
   * This function gets data by index.
   */
  async getDictationCorrectionByProfileId(
    profile_id: string,
  ): Promise<DictationCorrectionModel[]> {
    const index = createIndexProfileId(
      profile_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) dictation_correction by ProfileId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDictationCorrectionByProfileId(
    profile_id: string,
    data: DictationCorrectionModel
  ): Promise<DictationCorrectionModel[]> {
    const index = createIndexProfileId(
      profile_id
    );

    const values = DictationCorrectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete dictation_correction by ProfileId index
   */
  async deleteDictationCorrectionByProfileId(
    profile_id: string
  ): Promise<void> {
    const index = createIndexProfileId(
      profile_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to DictationCorrectionModel data array
   */
  private resultToData(values: Data[]): DictationCorrectionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return DictationCorrectionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as DictationCorrectionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized DictationCorrectionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is DictationCorrectionModel => item !== null);
  }
}

/**
 * Convert DictationCorrectionModel data to Value array
 */
function DictationCorrectionModelToValues(data: DictationCorrectionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'profile_id', type: DataType.string, defaultValue: '' },
    { key: 'original_audio_url', type: DataType.string, defaultValue: '' },
    { key: 'spoken_text', type: DataType.string, defaultValue: '' },
    { key: 'corrected_text', type: DataType.string, defaultValue: '' },
    { key: 'audio_duration', type: DataType.number, defaultValue: 0 },
    { key: 'is_applied', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof DictationCorrectionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to DictationCorrectionModel data
 */
function DictationCorrectionModelFromValues(values: Value[]): DictationCorrectionModel {
  const data: Partial<DictationCorrectionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'profile_id':
        data.profile_id = ParseValue(value, DataType.string) as string;
        break;
      case 'original_audio_url':
        data.original_audio_url = ParseValue(value, DataType.string) as string;
        break;
      case 'spoken_text':
        data.spoken_text = ParseValue(value, DataType.string) as string;
        break;
      case 'corrected_text':
        data.corrected_text = ParseValue(value, DataType.string) as string;
        break;
      case 'audio_duration':
        data.audio_duration = ParseValue(value, DataType.number) as number;
        break;
      case 'is_applied':
        data.is_applied = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as DictationCorrectionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for ProfileId fields
 */
function createIndexProfileId(
  profile_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, profile_id, 'profile_id'),
  ];

  return {
    fields: ['profile_id'],
    values
  };
}

export default DictationCorrectionORM;