// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user_settings.
// - Entity ID: 102019b22e952f17ec19c993e8f35a2b70b.
// - Entity Version: 102019b27a76a5f707fbe6865c0e6e7378a.
// - Task ID: 69417266b7d5b6b87ea7d926.
// - Task Root ID: 6931ddab540058f9d7a435e5.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for UserSettingsDictationMode
 */
export enum UserSettingsDictationMode {
  Unspecified = 0,
  press_to_talk = 1,
  free_hand = 2,
  command = 3,
  correction = 4,
}



/**
 * Interface for UserSettingsModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserSettingsModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  selected_microphone_id?: string | null;
  selected_microphone_label?: string | null;
  dictation_mode: UserSettingsDictationMode;
  auto_clean_enabled: boolean;
  shortcuts_enabled: boolean;
  selected_language: string;
  keyboard_mode_enabled: boolean;
}

/**
 * ORM class for UserSettings entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserSettingsORM {
  private static instance: UserSettingsORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b22e952f17ec19c993e8f35a2b70b';
    this.entityName = 'user_settings';
    this.entityVersion = '102019b27a76a5f707fbe6865c0e6e7378a';
    this.taskId = '69417266b7d5b6b87ea7d926';
    this.taskRootId = '6931ddab540058f9d7a435e5';
  }

  /**
   * Get singleton instance of UserSettingsORM
   */
  public static getInstance(): UserSettingsORM {
    if (!UserSettingsORM.instance) {
      UserSettingsORM.instance = new UserSettingsORM();
    }
    
    return UserSettingsORM.instance;
  }

  /**
   * Get all UserSettings records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUserSettings(): Promise<UserSettingsModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new UserSettings record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUserSettings(data: UserSettingsModel[]): Promise<UserSettingsModel[]> {
    const structured = data.map((item) => CreateData(UserSettingsModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all UserSettings records
   */
  async purgeAllUserSettings(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List UserSettings records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUserSettings(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserSettingsModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user_settings by Id index
   * This function gets data by index.
   */
  async getUserSettingsById(
    id: string,
  ): Promise<UserSettingsModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_settings by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSettingsById(
    id: string,
    data: UserSettingsModel
  ): Promise<UserSettingsModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserSettingsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_settings by Id index
   */
  async deleteUserSettingsById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_settings by DataCreator index
   * This function gets data by index.
   */
  async getUserSettingsByDataCreator(
    data_creator: string,
  ): Promise<UserSettingsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_settings by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSettingsByDataCreator(
    data_creator: string,
    data: UserSettingsModel
  ): Promise<UserSettingsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserSettingsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_settings by DataCreator index
   */
  async deleteUserSettingsByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_settings by DataUpdater index
   * This function gets data by index.
   */
  async getUserSettingsByDataUpdater(
    data_updater: string,
  ): Promise<UserSettingsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_settings by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSettingsByDataUpdater(
    data_updater: string,
    data: UserSettingsModel
  ): Promise<UserSettingsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserSettingsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_settings by DataUpdater index
   */
  async deleteUserSettingsByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_settings by UserId index
   * This function gets data by index.
   */
  async getUserSettingsByUserId(
    user_id: string,
  ): Promise<UserSettingsModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_settings by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSettingsByUserId(
    user_id: string,
    data: UserSettingsModel
  ): Promise<UserSettingsModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = UserSettingsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_settings by UserId index
   */
  async deleteUserSettingsByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserSettingsModel data array
   */
  private resultToData(values: Data[]): UserSettingsModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserSettingsModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserSettingsModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserSettingsModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserSettingsModel => item !== null);
  }
}

/**
 * Convert UserSettingsModel data to Value array
 */
function UserSettingsModelToValues(data: UserSettingsModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'selected_microphone_id', type: DataType.string, defaultValue: null },
    { key: 'selected_microphone_label', type: DataType.string, defaultValue: null },
    { key: 'dictation_mode', type: DataType.enumeration, defaultValue: 0 },
    { key: 'auto_clean_enabled', type: DataType.boolean, defaultValue: false },
    { key: 'shortcuts_enabled', type: DataType.boolean, defaultValue: false },
    { key: 'selected_language', type: DataType.string, defaultValue: '' },
    { key: 'keyboard_mode_enabled', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserSettingsModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserSettingsModel data
 */
function UserSettingsModelFromValues(values: Value[]): UserSettingsModel {
  const data: Partial<UserSettingsModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'selected_microphone_id':
        data.selected_microphone_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'selected_microphone_label':
        data.selected_microphone_label = ParseValue(value, DataType.string) as string | null;
        break;
      case 'dictation_mode':
        data.dictation_mode = ParseValue(value, DataType.enumeration) as UserSettingsDictationMode;
        break;
      case 'auto_clean_enabled':
        data.auto_clean_enabled = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'shortcuts_enabled':
        data.shortcuts_enabled = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'selected_language':
        data.selected_language = ParseValue(value, DataType.string) as string;
        break;
      case 'keyboard_mode_enabled':
        data.keyboard_mode_enabled = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as UserSettingsModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}

export default UserSettingsORM;