// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: downloaded_language.
// - Entity ID: 102019b22e952f275099a24e0f36ada7213.
// - Entity Version: 102019b27a76a5f707fbe6865c0e6e7378a.
// - Task ID: 69417266b7d5b6b87ea7d926.
// - Task Root ID: 6931ddab540058f9d7a435e5.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for DownloadedLanguageModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface DownloadedLanguageModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  language_code: string;
  language_name: string;
  is_downloaded: boolean;
  download_progress: number;
}

/**
 * ORM class for DownloadedLanguage entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class DownloadedLanguageORM {
  private static instance: DownloadedLanguageORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b22e952f275099a24e0f36ada7213';
    this.entityName = 'downloaded_language';
    this.entityVersion = '102019b27a76a5f707fbe6865c0e6e7378a';
    this.taskId = '69417266b7d5b6b87ea7d926';
    this.taskRootId = '6931ddab540058f9d7a435e5';
  }

  /**
   * Get singleton instance of DownloadedLanguageORM
   */
  public static getInstance(): DownloadedLanguageORM {
    if (!DownloadedLanguageORM.instance) {
      DownloadedLanguageORM.instance = new DownloadedLanguageORM();
    }
    
    return DownloadedLanguageORM.instance;
  }

  /**
   * Get all DownloadedLanguage records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllDownloadedLanguage(): Promise<DownloadedLanguageModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new DownloadedLanguage record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertDownloadedLanguage(data: DownloadedLanguageModel[]): Promise<DownloadedLanguageModel[]> {
    const structured = data.map((item) => CreateData(DownloadedLanguageModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all DownloadedLanguage records
   */
  async purgeAllDownloadedLanguage(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List DownloadedLanguage records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listDownloadedLanguage(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[DownloadedLanguageModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get downloaded_language by Id index
   * This function gets data by index.
   */
  async getDownloadedLanguageById(
    id: string,
  ): Promise<DownloadedLanguageModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) downloaded_language by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDownloadedLanguageById(
    id: string,
    data: DownloadedLanguageModel
  ): Promise<DownloadedLanguageModel[]> {
    const index = createIndexId(
      id
    );

    const values = DownloadedLanguageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete downloaded_language by Id index
   */
  async deleteDownloadedLanguageById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get downloaded_language by DataCreator index
   * This function gets data by index.
   */
  async getDownloadedLanguageByDataCreator(
    data_creator: string,
  ): Promise<DownloadedLanguageModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) downloaded_language by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDownloadedLanguageByDataCreator(
    data_creator: string,
    data: DownloadedLanguageModel
  ): Promise<DownloadedLanguageModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = DownloadedLanguageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete downloaded_language by DataCreator index
   */
  async deleteDownloadedLanguageByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get downloaded_language by DataUpdater index
   * This function gets data by index.
   */
  async getDownloadedLanguageByDataUpdater(
    data_updater: string,
  ): Promise<DownloadedLanguageModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) downloaded_language by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDownloadedLanguageByDataUpdater(
    data_updater: string,
    data: DownloadedLanguageModel
  ): Promise<DownloadedLanguageModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = DownloadedLanguageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete downloaded_language by DataUpdater index
   */
  async deleteDownloadedLanguageByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get downloaded_language by UserId index
   * This function gets data by index.
   */
  async getDownloadedLanguageByUserId(
    user_id: string,
  ): Promise<DownloadedLanguageModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) downloaded_language by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDownloadedLanguageByUserId(
    user_id: string,
    data: DownloadedLanguageModel
  ): Promise<DownloadedLanguageModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = DownloadedLanguageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete downloaded_language by UserId index
   */
  async deleteDownloadedLanguageByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get downloaded_language by LanguageCodeUserId index
   * This function gets data by index.
   */
  async getDownloadedLanguageByLanguageCodeUserId(
    language_code: string,
    user_id: string,
  ): Promise<DownloadedLanguageModel[]> {
    const index = createIndexLanguageCodeUserId(
      language_code,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) downloaded_language by LanguageCodeUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDownloadedLanguageByLanguageCodeUserId(
    language_code: string,
    user_id: string,
    data: DownloadedLanguageModel
  ): Promise<DownloadedLanguageModel[]> {
    const index = createIndexLanguageCodeUserId(
      language_code,
      user_id
    );

    const values = DownloadedLanguageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete downloaded_language by LanguageCodeUserId index
   */
  async deleteDownloadedLanguageByLanguageCodeUserId(
    language_code: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexLanguageCodeUserId(
      language_code,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to DownloadedLanguageModel data array
   */
  private resultToData(values: Data[]): DownloadedLanguageModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return DownloadedLanguageModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as DownloadedLanguageModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized DownloadedLanguageModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is DownloadedLanguageModel => item !== null);
  }
}

/**
 * Convert DownloadedLanguageModel data to Value array
 */
function DownloadedLanguageModelToValues(data: DownloadedLanguageModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'language_code', type: DataType.string, defaultValue: '' },
    { key: 'language_name', type: DataType.string, defaultValue: '' },
    { key: 'is_downloaded', type: DataType.boolean, defaultValue: false },
    { key: 'download_progress', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof DownloadedLanguageModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to DownloadedLanguageModel data
 */
function DownloadedLanguageModelFromValues(values: Value[]): DownloadedLanguageModel {
  const data: Partial<DownloadedLanguageModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'language_code':
        data.language_code = ParseValue(value, DataType.string) as string;
        break;
      case 'language_name':
        data.language_name = ParseValue(value, DataType.string) as string;
        break;
      case 'is_downloaded':
        data.is_downloaded = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'download_progress':
        data.download_progress = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as DownloadedLanguageModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for LanguageCodeUserId fields
 */
function createIndexLanguageCodeUserId(
  language_code: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, language_code, 'language_code'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['language_code', 'user_id'],
    values
  };
}

export default DownloadedLanguageORM;