// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: keyboard_shortcut.
// - Entity ID: 102019b22e952f272e18a05bf92475c3030.
// - Entity Version: 102019b27a76a5f707fbe6865c0e6e7378a.
// - Task ID: 69417266b7d5b6b87ea7d926.
// - Task Root ID: 6931ddab540058f9d7a435e5.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for KeyboardShortcutModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface KeyboardShortcutModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  action: string;
  key_combination: string;
  is_enabled: boolean;
}

/**
 * ORM class for KeyboardShortcut entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class KeyboardShortcutORM {
  private static instance: KeyboardShortcutORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b22e952f272e18a05bf92475c3030';
    this.entityName = 'keyboard_shortcut';
    this.entityVersion = '102019b27a76a5f707fbe6865c0e6e7378a';
    this.taskId = '69417266b7d5b6b87ea7d926';
    this.taskRootId = '6931ddab540058f9d7a435e5';
  }

  /**
   * Get singleton instance of KeyboardShortcutORM
   */
  public static getInstance(): KeyboardShortcutORM {
    if (!KeyboardShortcutORM.instance) {
      KeyboardShortcutORM.instance = new KeyboardShortcutORM();
    }
    
    return KeyboardShortcutORM.instance;
  }

  /**
   * Get all KeyboardShortcut records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllKeyboardShortcut(): Promise<KeyboardShortcutModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new KeyboardShortcut record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertKeyboardShortcut(data: KeyboardShortcutModel[]): Promise<KeyboardShortcutModel[]> {
    const structured = data.map((item) => CreateData(KeyboardShortcutModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all KeyboardShortcut records
   */
  async purgeAllKeyboardShortcut(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List KeyboardShortcut records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listKeyboardShortcut(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[KeyboardShortcutModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get keyboard_shortcut by Id index
   * This function gets data by index.
   */
  async getKeyboardShortcutById(
    id: string,
  ): Promise<KeyboardShortcutModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) keyboard_shortcut by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setKeyboardShortcutById(
    id: string,
    data: KeyboardShortcutModel
  ): Promise<KeyboardShortcutModel[]> {
    const index = createIndexId(
      id
    );

    const values = KeyboardShortcutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete keyboard_shortcut by Id index
   */
  async deleteKeyboardShortcutById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get keyboard_shortcut by DataCreator index
   * This function gets data by index.
   */
  async getKeyboardShortcutByDataCreator(
    data_creator: string,
  ): Promise<KeyboardShortcutModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) keyboard_shortcut by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setKeyboardShortcutByDataCreator(
    data_creator: string,
    data: KeyboardShortcutModel
  ): Promise<KeyboardShortcutModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = KeyboardShortcutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete keyboard_shortcut by DataCreator index
   */
  async deleteKeyboardShortcutByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get keyboard_shortcut by DataUpdater index
   * This function gets data by index.
   */
  async getKeyboardShortcutByDataUpdater(
    data_updater: string,
  ): Promise<KeyboardShortcutModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) keyboard_shortcut by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setKeyboardShortcutByDataUpdater(
    data_updater: string,
    data: KeyboardShortcutModel
  ): Promise<KeyboardShortcutModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = KeyboardShortcutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete keyboard_shortcut by DataUpdater index
   */
  async deleteKeyboardShortcutByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get keyboard_shortcut by UserId index
   * This function gets data by index.
   */
  async getKeyboardShortcutByUserId(
    user_id: string,
  ): Promise<KeyboardShortcutModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) keyboard_shortcut by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setKeyboardShortcutByUserId(
    user_id: string,
    data: KeyboardShortcutModel
  ): Promise<KeyboardShortcutModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = KeyboardShortcutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete keyboard_shortcut by UserId index
   */
  async deleteKeyboardShortcutByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get keyboard_shortcut by KeyCombinationUserId index
   * This function gets data by index.
   */
  async getKeyboardShortcutByKeyCombinationUserId(
    key_combination: string,
    user_id: string,
  ): Promise<KeyboardShortcutModel[]> {
    const index = createIndexKeyCombinationUserId(
      key_combination,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) keyboard_shortcut by KeyCombinationUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setKeyboardShortcutByKeyCombinationUserId(
    key_combination: string,
    user_id: string,
    data: KeyboardShortcutModel
  ): Promise<KeyboardShortcutModel[]> {
    const index = createIndexKeyCombinationUserId(
      key_combination,
      user_id
    );

    const values = KeyboardShortcutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete keyboard_shortcut by KeyCombinationUserId index
   */
  async deleteKeyboardShortcutByKeyCombinationUserId(
    key_combination: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexKeyCombinationUserId(
      key_combination,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to KeyboardShortcutModel data array
   */
  private resultToData(values: Data[]): KeyboardShortcutModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return KeyboardShortcutModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as KeyboardShortcutModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized KeyboardShortcutModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is KeyboardShortcutModel => item !== null);
  }
}

/**
 * Convert KeyboardShortcutModel data to Value array
 */
function KeyboardShortcutModelToValues(data: KeyboardShortcutModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'action', type: DataType.string, defaultValue: '' },
    { key: 'key_combination', type: DataType.string, defaultValue: '' },
    { key: 'is_enabled', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof KeyboardShortcutModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to KeyboardShortcutModel data
 */
function KeyboardShortcutModelFromValues(values: Value[]): KeyboardShortcutModel {
  const data: Partial<KeyboardShortcutModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'action':
        data.action = ParseValue(value, DataType.string) as string;
        break;
      case 'key_combination':
        data.key_combination = ParseValue(value, DataType.string) as string;
        break;
      case 'is_enabled':
        data.is_enabled = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as KeyboardShortcutModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for KeyCombinationUserId fields
 */
function createIndexKeyCombinationUserId(
  key_combination: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, key_combination, 'key_combination'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['key_combination', 'user_id'],
    values
  };
}

export default KeyboardShortcutORM;