// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: transcription_session.
// - Entity ID: 102019b2305f23779a88d10d0bcf39bdc9f.
// - Entity Version: 102019b27a76a5f707fbe6865c0e6e7378a.
// - Task ID: 69417266b7d5b6b87ea7d926.
// - Task Root ID: 6931ddab540058f9d7a435e5.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for TranscriptionSessionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface TranscriptionSessionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  profile_id: string;
  title: string;
  transcribed_text?: string | null;
  duration: number;
}

/**
 * ORM class for TranscriptionSession entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class TranscriptionSessionORM {
  private static instance: TranscriptionSessionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b2305f23779a88d10d0bcf39bdc9f';
    this.entityName = 'transcription_session';
    this.entityVersion = '102019b27a76a5f707fbe6865c0e6e7378a';
    this.taskId = '69417266b7d5b6b87ea7d926';
    this.taskRootId = '6931ddab540058f9d7a435e5';
  }

  /**
   * Get singleton instance of TranscriptionSessionORM
   */
  public static getInstance(): TranscriptionSessionORM {
    if (!TranscriptionSessionORM.instance) {
      TranscriptionSessionORM.instance = new TranscriptionSessionORM();
    }
    
    return TranscriptionSessionORM.instance;
  }

  /**
   * Get all TranscriptionSession records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllTranscriptionSession(): Promise<TranscriptionSessionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new TranscriptionSession record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertTranscriptionSession(data: TranscriptionSessionModel[]): Promise<TranscriptionSessionModel[]> {
    const structured = data.map((item) => CreateData(TranscriptionSessionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all TranscriptionSession records
   */
  async purgeAllTranscriptionSession(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List TranscriptionSession records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listTranscriptionSession(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[TranscriptionSessionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get transcription_session by Id index
   * This function gets data by index.
   */
  async getTranscriptionSessionById(
    id: string,
  ): Promise<TranscriptionSessionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transcription_session by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTranscriptionSessionById(
    id: string,
    data: TranscriptionSessionModel
  ): Promise<TranscriptionSessionModel[]> {
    const index = createIndexId(
      id
    );

    const values = TranscriptionSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transcription_session by Id index
   */
  async deleteTranscriptionSessionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transcription_session by DataCreator index
   * This function gets data by index.
   */
  async getTranscriptionSessionByDataCreator(
    data_creator: string,
  ): Promise<TranscriptionSessionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transcription_session by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTranscriptionSessionByDataCreator(
    data_creator: string,
    data: TranscriptionSessionModel
  ): Promise<TranscriptionSessionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = TranscriptionSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transcription_session by DataCreator index
   */
  async deleteTranscriptionSessionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transcription_session by DataUpdater index
   * This function gets data by index.
   */
  async getTranscriptionSessionByDataUpdater(
    data_updater: string,
  ): Promise<TranscriptionSessionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transcription_session by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTranscriptionSessionByDataUpdater(
    data_updater: string,
    data: TranscriptionSessionModel
  ): Promise<TranscriptionSessionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = TranscriptionSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transcription_session by DataUpdater index
   */
  async deleteTranscriptionSessionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transcription_session by CreateTimeUserId index
   * This function gets data by index.
   */
  async getTranscriptionSessionByCreateTimeUserId(
    create_time: string,
    user_id: string,
  ): Promise<TranscriptionSessionModel[]> {
    const index = createIndexCreateTimeUserId(
      create_time,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transcription_session by CreateTimeUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTranscriptionSessionByCreateTimeUserId(
    create_time: string,
    user_id: string,
    data: TranscriptionSessionModel
  ): Promise<TranscriptionSessionModel[]> {
    const index = createIndexCreateTimeUserId(
      create_time,
      user_id
    );

    const values = TranscriptionSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transcription_session by CreateTimeUserId index
   */
  async deleteTranscriptionSessionByCreateTimeUserId(
    create_time: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexCreateTimeUserId(
      create_time,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transcription_session by ProfileId index
   * This function gets data by index.
   */
  async getTranscriptionSessionByProfileId(
    profile_id: string,
  ): Promise<TranscriptionSessionModel[]> {
    const index = createIndexProfileId(
      profile_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transcription_session by ProfileId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTranscriptionSessionByProfileId(
    profile_id: string,
    data: TranscriptionSessionModel
  ): Promise<TranscriptionSessionModel[]> {
    const index = createIndexProfileId(
      profile_id
    );

    const values = TranscriptionSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transcription_session by ProfileId index
   */
  async deleteTranscriptionSessionByProfileId(
    profile_id: string
  ): Promise<void> {
    const index = createIndexProfileId(
      profile_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to TranscriptionSessionModel data array
   */
  private resultToData(values: Data[]): TranscriptionSessionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return TranscriptionSessionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as TranscriptionSessionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized TranscriptionSessionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is TranscriptionSessionModel => item !== null);
  }
}

/**
 * Convert TranscriptionSessionModel data to Value array
 */
function TranscriptionSessionModelToValues(data: TranscriptionSessionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'profile_id', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'transcribed_text', type: DataType.string, defaultValue: null },
    { key: 'duration', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof TranscriptionSessionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to TranscriptionSessionModel data
 */
function TranscriptionSessionModelFromValues(values: Value[]): TranscriptionSessionModel {
  const data: Partial<TranscriptionSessionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'profile_id':
        data.profile_id = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'transcribed_text':
        data.transcribed_text = ParseValue(value, DataType.string) as string | null;
        break;
      case 'duration':
        data.duration = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as TranscriptionSessionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for CreateTimeUserId fields
 */
function createIndexCreateTimeUserId(
  create_time: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['create_time', 'user_id'],
    values
  };
}
/**
 * Create index for ProfileId fields
 */
function createIndexProfileId(
  profile_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, profile_id, 'profile_id'),
  ];

  return {
    fields: ['profile_id'],
    values
  };
}

export default TranscriptionSessionORM;