// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: personal_dictionary_entry.
// - Entity ID: 102019b2473057874c9a1176b87a791cdb6.
// - Entity Version: 102019b27a76a5f707fbe6865c0e6e7378a.
// - Task ID: 69417266b7d5b6b87ea7d926.
// - Task Root ID: 6931ddab540058f9d7a435e5.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for PersonalDictionaryEntryEntryType
 */
export enum PersonalDictionaryEntryEntryType {
  Unspecified = 0,
  word = 1,
  phrase = 2,
  spelling = 3,
  casing = 4,
}



/**
 * Interface for PersonalDictionaryEntryModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface PersonalDictionaryEntryModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  profile_id: string;
  user_id: string;
  original_text: string;
  replacement_text: string;
  entry_type: PersonalDictionaryEntryEntryType;
  is_always_replace: boolean;
  pronunciation_hint?: string | null;
  priority: number;
  is_enabled: boolean;
}

/**
 * ORM class for PersonalDictionaryEntry entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class PersonalDictionaryEntryORM {
  private static instance: PersonalDictionaryEntryORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b2473057874c9a1176b87a791cdb6';
    this.entityName = 'personal_dictionary_entry';
    this.entityVersion = '102019b27a76a5f707fbe6865c0e6e7378a';
    this.taskId = '69417266b7d5b6b87ea7d926';
    this.taskRootId = '6931ddab540058f9d7a435e5';
  }

  /**
   * Get singleton instance of PersonalDictionaryEntryORM
   */
  public static getInstance(): PersonalDictionaryEntryORM {
    if (!PersonalDictionaryEntryORM.instance) {
      PersonalDictionaryEntryORM.instance = new PersonalDictionaryEntryORM();
    }
    
    return PersonalDictionaryEntryORM.instance;
  }

  /**
   * Get all PersonalDictionaryEntry records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllPersonalDictionaryEntry(): Promise<PersonalDictionaryEntryModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new PersonalDictionaryEntry record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertPersonalDictionaryEntry(data: PersonalDictionaryEntryModel[]): Promise<PersonalDictionaryEntryModel[]> {
    const structured = data.map((item) => CreateData(PersonalDictionaryEntryModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all PersonalDictionaryEntry records
   */
  async purgeAllPersonalDictionaryEntry(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List PersonalDictionaryEntry records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listPersonalDictionaryEntry(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[PersonalDictionaryEntryModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get personal_dictionary_entry by Id index
   * This function gets data by index.
   */
  async getPersonalDictionaryEntryById(
    id: string,
  ): Promise<PersonalDictionaryEntryModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) personal_dictionary_entry by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPersonalDictionaryEntryById(
    id: string,
    data: PersonalDictionaryEntryModel
  ): Promise<PersonalDictionaryEntryModel[]> {
    const index = createIndexId(
      id
    );

    const values = PersonalDictionaryEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete personal_dictionary_entry by Id index
   */
  async deletePersonalDictionaryEntryById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get personal_dictionary_entry by DataCreator index
   * This function gets data by index.
   */
  async getPersonalDictionaryEntryByDataCreator(
    data_creator: string,
  ): Promise<PersonalDictionaryEntryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) personal_dictionary_entry by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPersonalDictionaryEntryByDataCreator(
    data_creator: string,
    data: PersonalDictionaryEntryModel
  ): Promise<PersonalDictionaryEntryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = PersonalDictionaryEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete personal_dictionary_entry by DataCreator index
   */
  async deletePersonalDictionaryEntryByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get personal_dictionary_entry by DataUpdater index
   * This function gets data by index.
   */
  async getPersonalDictionaryEntryByDataUpdater(
    data_updater: string,
  ): Promise<PersonalDictionaryEntryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) personal_dictionary_entry by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPersonalDictionaryEntryByDataUpdater(
    data_updater: string,
    data: PersonalDictionaryEntryModel
  ): Promise<PersonalDictionaryEntryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = PersonalDictionaryEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete personal_dictionary_entry by DataUpdater index
   */
  async deletePersonalDictionaryEntryByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get personal_dictionary_entry by ProfileId index
   * This function gets data by index.
   */
  async getPersonalDictionaryEntryByProfileId(
    profile_id: string,
  ): Promise<PersonalDictionaryEntryModel[]> {
    const index = createIndexProfileId(
      profile_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) personal_dictionary_entry by ProfileId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPersonalDictionaryEntryByProfileId(
    profile_id: string,
    data: PersonalDictionaryEntryModel
  ): Promise<PersonalDictionaryEntryModel[]> {
    const index = createIndexProfileId(
      profile_id
    );

    const values = PersonalDictionaryEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete personal_dictionary_entry by ProfileId index
   */
  async deletePersonalDictionaryEntryByProfileId(
    profile_id: string
  ): Promise<void> {
    const index = createIndexProfileId(
      profile_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get personal_dictionary_entry by UserId index
   * This function gets data by index.
   */
  async getPersonalDictionaryEntryByUserId(
    user_id: string,
  ): Promise<PersonalDictionaryEntryModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) personal_dictionary_entry by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPersonalDictionaryEntryByUserId(
    user_id: string,
    data: PersonalDictionaryEntryModel
  ): Promise<PersonalDictionaryEntryModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = PersonalDictionaryEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete personal_dictionary_entry by UserId index
   */
  async deletePersonalDictionaryEntryByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get personal_dictionary_entry by OriginalTextProfileId index
   * This function gets data by index.
   */
  async getPersonalDictionaryEntryByOriginalTextProfileId(
    original_text: string,
    profile_id: string,
  ): Promise<PersonalDictionaryEntryModel[]> {
    const index = createIndexOriginalTextProfileId(
      original_text,
      profile_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) personal_dictionary_entry by OriginalTextProfileId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPersonalDictionaryEntryByOriginalTextProfileId(
    original_text: string,
    profile_id: string,
    data: PersonalDictionaryEntryModel
  ): Promise<PersonalDictionaryEntryModel[]> {
    const index = createIndexOriginalTextProfileId(
      original_text,
      profile_id
    );

    const values = PersonalDictionaryEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete personal_dictionary_entry by OriginalTextProfileId index
   */
  async deletePersonalDictionaryEntryByOriginalTextProfileId(
    original_text: string,
    profile_id: string
  ): Promise<void> {
    const index = createIndexOriginalTextProfileId(
      original_text,
      profile_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to PersonalDictionaryEntryModel data array
   */
  private resultToData(values: Data[]): PersonalDictionaryEntryModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return PersonalDictionaryEntryModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as PersonalDictionaryEntryModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized PersonalDictionaryEntryModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is PersonalDictionaryEntryModel => item !== null);
  }
}

/**
 * Convert PersonalDictionaryEntryModel data to Value array
 */
function PersonalDictionaryEntryModelToValues(data: PersonalDictionaryEntryModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'profile_id', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'original_text', type: DataType.string, defaultValue: '' },
    { key: 'replacement_text', type: DataType.string, defaultValue: '' },
    { key: 'entry_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'is_always_replace', type: DataType.boolean, defaultValue: false },
    { key: 'pronunciation_hint', type: DataType.string, defaultValue: null },
    { key: 'priority', type: DataType.number, defaultValue: 0 },
    { key: 'is_enabled', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof PersonalDictionaryEntryModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to PersonalDictionaryEntryModel data
 */
function PersonalDictionaryEntryModelFromValues(values: Value[]): PersonalDictionaryEntryModel {
  const data: Partial<PersonalDictionaryEntryModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'profile_id':
        data.profile_id = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'original_text':
        data.original_text = ParseValue(value, DataType.string) as string;
        break;
      case 'replacement_text':
        data.replacement_text = ParseValue(value, DataType.string) as string;
        break;
      case 'entry_type':
        data.entry_type = ParseValue(value, DataType.enumeration) as PersonalDictionaryEntryEntryType;
        break;
      case 'is_always_replace':
        data.is_always_replace = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'pronunciation_hint':
        data.pronunciation_hint = ParseValue(value, DataType.string) as string | null;
        break;
      case 'priority':
        data.priority = ParseValue(value, DataType.number) as number;
        break;
      case 'is_enabled':
        data.is_enabled = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as PersonalDictionaryEntryModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for ProfileId fields
 */
function createIndexProfileId(
  profile_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, profile_id, 'profile_id'),
  ];

  return {
    fields: ['profile_id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for OriginalTextProfileId fields
 */
function createIndexOriginalTextProfileId(
  original_text: string,
  profile_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, original_text, 'original_text'),
    CreateValue(DataType.string, profile_id, 'profile_id'),
  ];

  return {
    fields: ['original_text', 'profile_id'],
    values
  };
}

export default PersonalDictionaryEntryORM;